apiVersion: v1
kind: Pod

metadata:
  name: pod-env-vol
  namespace: default
  

spec:
  containers:
    - name: my-name
      image: nginx
      envFrom:
        - configMapRef:  # referencia um configmap
        # - secretRef:   # referencia um secret
            name: config-map
      volumeMounts:
        - name:  my-vol
          mountPath: /etc/my-vol
          readOnly: true

  volumes:
    - name: my-vol
      configMap:
        name: config-map
      # secret:
      #   secretName: secret-name