apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-deployment
  labels:
    app: frontend

spec:
  template:
    metadata:
      name: pod-nginx
      labels:
        env: homolog

    spec:
       containers: 
         - name: nginx-container
           image: nginx

  selector:
    matchLabels:
      env: homolog

  replicas: 3
