apiVersion: v1
kind: Pod

metadata:
  name: resources-pod

spec:
  containers:
    - name: apache-container
      image: httpd

      resources:
        requests: # definição dos recursos mínimos para esse Pod
          cpu: "500m"
          memory: "128Mi"

        limits: # definição de limites de recursos para esse Pod
          cpu: "1000m"
          memory: "256Mi"


    - name: redis-container
      image: redis

      resources:
        requests: # definição dos recursos mínimos para esse Pod
          cpu: "400m"
          memory: "64Mi"

        limits: # definição de limites de recursos para esse Pod
          cpu: "500m"
          memory: "128Mi"