apiVersion: v1
kind: Pod

metadata:
  name: pod-env-test
  namespace: default
  

spec:
  containers:
    - name: secret-optional
      image: nginx
      envFrom:
        - secretRef:
            name: test-secret
            optional: true   # o Pod vai subir, mesmo que o secret não tenha sido criado
      volumeMounts:
        - name:  my-vol
          mountPath: /etc/my-vol
          readOnly: true

  volumes:
    - name: my-vol
      secret:
        name: test-secret
        optional: true   # o Volume vai ser criado, mesmo que o secret não tenha sido criado