apiVersion: v1
kind: Pod

metadata:
  name: tomcat-pod
  labels:
    apps: app-java

spec:
  containers:
    - name: container-tomcat
      image: tomcat
      env:
        - name: VAR_1
          value: teste
        - name: VAR_2
          value: teste2