apiVersion: v1
kind: Pod

metadata:
  name: redis-pod

spec:
  containers:
    - name: redis-container
      image: redis
      volumeMounts:
        - name: cache-storage
          mountPath: /my-volume # pasta dentro do Pod onde ficará minha persistência de dados

  volumes:
    - name: cache-storage
      emptyDir: {}


---

apiVersion: v1
kind: Pod

metadata:
  name: tomcat-pod

spec:
  containers:
    - name: tomcat-container
      image: tomcat
      volumeMounts:
        - name: hostpath-vol
          mountPath: /my-data # pasta dentro do Worker Node onde ficará minha persistência de dados          
  volumes:
    - name: hostpath-vol
      hostPath:
        path: /var/lib/2-persist