apiVersion: v1
kind: Service
metadata:
  name: svc-sts
spec:
  ports:
    - port: 80
  clusterIP: None  # esse campo com None é para criar um Headless Service
  selector:
    app: nginx-app-pods

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  selector:  # define o pod ele será iniciado
    matchLabels:
      app: nginx-app-pods
  
  serviceName: svc-sts  # nome do serviço que irá controlar os pods
  
  replicas: 3
  
  template:
    metadata:
      labels:
        app: nginx-app-pods
    spec:
      containers:
        - name: my-container
          image: nginx:1.23.1
          volumeMounts:
            - name: my-persistent-volume
              mountPath:  /usr/share/nginx/html

  volumeClaimTemplates:  # estão as específicações de como eu quero cada um de meus volumes. Aqui tem a criação dos volumes e a associação deles com os pods (um volume e um claim)
    - metadata:
        name: my-persistent-volume  # ao criar um claim irá associar ele ao volume usado no pod nginx-app-pods
      spec:
        accessModes: [ "ReadWriteOnce" ]  # diz que esse volume tem permissão de leitura e escrita
        resources:
          requests:
            storage: 1Gi  # defininfo que esse volume terá 1GB de armazenamento